"""
IDS alert model with severity, cooldown and deduplication keys.
"""

import hashlib
import time
import threading
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

from app.utils.time_utils import format_timestamp


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


SEVERITY_COLORS = {
    Severity.LOW: "#4CAF50",
    Severity.MEDIUM: "#FB8C00",
    Severity.HIGH: "#E64A19",
    Severity.CRITICAL: "#B71C1C",
}


ALERT_SYN_FLOOD = "Possible SYN Flood"
ALERT_PORT_SCAN = "Possible Port Scan"
ALERT_ICMP_FLOOD = "Possible ICMP Flood"
ALERT_UDP_FLOOD = "Possible UDP Flood"
ALERT_PING_SWEEP = "Possible Ping Sweep"
ALERT_SUSPICIOUS_FLAGS = "Suspicious TCP Flags"
ALERT_PACKET_RATE = "Abnormal Packet Rate"
ALERT_DEMO = "Demo / Test Event"


@dataclass
class IDSAlert:
    alert_id: str
    alert_type: str
    severity: Severity
    timestamp: float
    source_ip: str = ""
    destination_ip: str = ""
    source_port: int = 0
    destination_port: int = 0
    observed_rate: float = 0.0
    threshold: float = 0.0
    ports_count: int = 0
    time_window_seconds: int = 0
    message: str = ""
    recommended_action: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    is_demo: bool = False

    def to_row(self) -> tuple:
        return (
            format_timestamp(self.timestamp),
            self.severity.value,
            self.alert_type,
            self.source_ip,
            self.destination_ip,
            self.ports_count or (
                f"{self.observed_rate:.1f}/s" if self.observed_rate else ""
            ),
            "DEMO" if self.is_demo else "ACTIVE",
        )

    def summary(self) -> str:
        lines = [
            f"Type: {self.alert_type}",
            f"Severity: {self.severity.value}",
            f"Timestamp: {format_timestamp(self.timestamp)}",
        ]
        if self.source_ip:
            lines.append(f"Source IP: {self.source_ip}")
        if self.destination_ip:
            lines.append(f"Destination IP: {self.destination_ip}")
        if self.source_port or self.destination_port:
            lines.append(
                f"Ports: src={self.source_port or '-'} / dst={self.destination_port or '-'}"
            )
        if self.observed_rate:
            lines.append(f"Observed rate: {self.observed_rate:.1f} pkts/s")
        if self.threshold:
            lines.append(f"Threshold: {self.threshold:.1f} pkts/s")
        if self.ports_count:
            lines.append(f"Distinct ports: {self.ports_count}")
        if self.time_window_seconds:
            lines.append(f"Time window: {self.time_window_seconds}s")
        if self.message:
            lines.append(f"Observation: {self.message}")
        if self.recommended_action:
            lines.append(f"Recommended action: {self.recommended_action}")
        if self.is_demo:
            lines.append("NOTE: This alert was generated by DEMO/TEST mode.")
        return "\n".join(lines)

    def email_body(self) -> str:
        body = [
            "Network Packet Sniffer IDS Alert",
            "=" * 40,
            self.summary(),
        ]
        if self.details:
            body.append("")
            body.append("Additional Details:")
            for k, v in self.details.items():
                body.append(f"  - {k}: {v}")
        return "\n".join(body)

    def deduplication_key(self) -> str:
        base = (
            f"{self.alert_type}|{self.source_ip}|{self.destination_ip}|"
            f"{self.source_port}|{self.destination_port}"
        )
        return hashlib.sha256(base.encode("utf-8")).hexdigest()[:16]


class AlertManager:
    def __init__(self, cooldown_seconds: int = 300, max_alerts: int = 5000):
        self._lock = threading.RLock()
        self._alerts: List[IDSAlert] = []
        self._last_fired: Dict[str, float] = {}
        self._cooldown_seconds = max(0, int(cooldown_seconds))
        self._max_alerts = max(100, int(max_alerts))
        self._total_alerts = 0
        self._severity_counts: Dict[Severity, int] = {s: 0 for s in Severity}
        self._listeners: List[Any] = []

    def set_cooldown(self, seconds: int) -> None:
        with self._lock:
            self._cooldown_seconds = max(0, int(seconds))

    def add_listener(self, callback: Any) -> None:
        with self._lock:
            self._listeners.append(callback)

    def _notify_listeners(self, alert: IDSAlert) -> None:
        for cb in list(self._listeners):
            try:
                cb(alert)
            except Exception:
                pass

    def should_fire(self, alert: IDSAlert) -> bool:
        with self._lock:
            if self._cooldown_seconds <= 0:
                return True
            key = alert.deduplication_key()
            last = self._last_fired.get(key, 0.0)
            return (time.time() - last) >= self._cooldown_seconds

    def record(self, alert: IDSAlert, force: bool = False) -> bool:
        if alert is None:
            return False
        with self._lock:
            if not force and not self.should_fire(alert):
                return False
            self._last_fired[alert.deduplication_key()] = time.time()
            self._alerts.append(alert)
            if len(self._alerts) > self._max_alerts:
                self._alerts = self._alerts[-self._max_alerts:]
            self._total_alerts += 1
            self._severity_counts[alert.severity] = self._severity_counts.get(alert.severity, 0) + 1
        try:
            self._notify_listeners(alert)
        except Exception:
            pass
        return True

    def total_alerts(self) -> int:
        with self._lock:
            return self._total_alerts

    def active_count(self) -> int:
        with self._lock:
            return len(self._alerts)

    def severity_counts(self) -> Dict[Severity, int]:
        with self._lock:
            return dict(self._severity_counts)

    def last_alert(self) -> Optional[IDSAlert]:
        with self._lock:
            return self._alerts[-1] if self._alerts else None

    def list_alerts(self, limit: Optional[int] = None) -> List[IDSAlert]:
        with self._lock:
            if limit is None:
                return list(self._alerts)
            limit = max(0, int(limit))
            return list(self._alerts[-limit:])

    def clear(self) -> None:
        with self._lock:
            self._alerts.clear()
            self._last_fired.clear()
            self._total_alerts = 0
            self._severity_counts = {s: 0 for s in Severity}

    def highest_severity(self) -> Severity:
        with self._lock:
            order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]
            for s in order:
                if self._severity_counts.get(s, 0) > 0:
                    return s
            return Severity.LOW
